name: Notify Discord on Pull Request

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord via curl
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          MESSAGE="🚀 **Pull Request Update**\n- [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})\n- **Title:** ${{ github.event.pull_request.title }}\n- **Author:** ${{ github.event.pull_request.user.login }}\n- **Action:** ${{ github.event.action }}"

          jq -n --arg content "$MESSAGE" '{content: $content}' > payload.json

          curl -H "Content-Type: application/json" \
               -X POST \
               -d @payload.json \
               $DISCORD_WEBHOOK