name: Notify Discord on Pull Request

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord via curl
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          MESSAGE="🚀 **Pull Request Update**
          - [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})
          - **Title:** ${{ github.event.pull_request.title }}
          - **Author:** ${{ github.event.pull_request.user.login }}
          - **Action:** ${{ github.event.action }}"
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               $DISCORD_WEBHOOK