name: Notify Discord on Pull Request

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🚀 **Pull Request Update**
            - [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})
            - **Title:** ${{ github.event.pull_request.title }}
            - **Author:** ${{ github.event.pull_request.user.login }}
            - **Action:** ${{ github.event.action }}